version: '3.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - "somenetwork"
    environment:
      - "discovery.type=single-node"
  kinaba-eleastic:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - "5601:5601"
    links:
      - "elasticsearch:elasticsearch"
    networks:
      - "somenetwork"
networks:
    somenetwork:
      driver: bridge


